#!/usr/bin/env php
<?php
require_once('vendor/autoload.php');
use Symfony\Component\Console\Application;
use UlysseCounter\DataSendCommand;
use UlysseCounter\GetWordListCommand;
 
$console = new Application();
$console->add(new DataSendCommand);
$console->add(new GetWordListCommand);
$console->run();